name: Build jobs

on:
  pull_request

jobs:
  build_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build Anoma + Proxy image
        run: |
          make build
